insert into product(name, category, price, manufacturer, unitInStock, description) values ("아이폰xs", "핸드폰", 50000, "애플", 100, "튼튼해요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("갤럭시10", "핸드폰", 40000, "삼상전자", 200, "저렴해요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("세탁기", "가전", 30000, "LG", 200, "튼튼해요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("맥북", "컴퓨터", 10000, "애플", 40, "비싸요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("아이폰6", "핸드폰", 30000, "애플", 70, "튼튼해요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("아디다스운동화", "운동화", 7000, "아디다스", 600, "편해요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("나이키운동화", "운동화", 8000, "나이키", 90, "오래 신어요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("아이폰11 pro", "핸드폰", 50000, "애플", 250, "최신형")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("그램", "컴퓨터", 9000, "LG", 300, "튼튼하고 오래써요")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("삼성노트북", "컴퓨터", 50000, "삼성전자", 450, "저렴해요")